---
- name: Attach the VM's network adapter to the new portgroup
  when: vcenter_vm_name | default('') | length > 0
  delegate_to: localhost
  community.vmware.vmware_guest_network:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vmware_validate_certs }}"
    name: "{{ vcenter_vm_name }}"
    label: "{{ vcenter_vm_network_adapter_label }}"
    network_name: "{{ vcenter_vlan.name }}"
    switch: "{{ vcenter_vlan.switch_name }}"
    connected: true
    start_connected: true
    state: present
