---
oneview_hostname: oneview.example.local
oneview_username: "{{ vault_oneview_username }}"
oneview_password: "{{ vault_oneview_password }}"
oneview_auth_login_domain: LOCAL
oneview_api_version: 3000
oneview_server_hardware_name: "Encl1, bay 1"
oneview_server_profile_name: ""
