---
- name: Create or maintain the local automation administrator
  delegate_to: scvmm_conf_target
  no_log: true
  ansible.windows.win_user:
    name: "{{ scvmm_conf_local_admin.name }}"
    password: "{{ scvmm_conf_local_admin.password }}"
    update_password: always
    password_never_expires: true
    groups:
      - Administrators
    groups_action: add
    state: present
