---
- name: Configure NetBackup SNMP notification settings
  ansible.builtin.uri:
    url: "https://{{ netbackup_conf_hostname }}:{{ netbackup_conf_port }}{{ netbackup_conf_snmp_endpoint }}"
    method: "{{ netbackup_conf_snmp_method }}"
    headers:
      Content-Type: "{{ netbackup_conf_media_type }}"
      Accept: "{{ netbackup_conf_media_type }}"
      Authorization: "Bearer {{ netbackup_conf_access_token }}"
    body_format: json
    body: "{{ netbackup_conf_snmp_configuration }}"
    validate_certs: "{{ netbackup_conf_validate_certs }}"
    status_code: [200, 201, 202, 204]
  register: netbackup_conf_snmp_result
  changed_when: netbackup_conf_snmp_result.status in [201, 202, 204]
  no_log: true
